name: check-copyright
on: [push, pull_request]
jobs:
  check-copyright:
    name: check-copyright
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check copyright
      run: sh ./.github/scripts/check_copyright.sh 
      shell: bash 
