name: CI golang

on: [push, pull_request]

jobs:
  call-workflow-ci:
    uses: ivvist/ci-action/.github/workflows/ci_reuse_go_norebuild.yml@master
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
